/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Business Man.glb --transform --types -o src/components/Business Man.tsx 
Files: public/models/Business Man.glb [1.53MB] > /workspaces/mesh-mates/packages/client/src/components/Business Man-transformed.glb [427.63KB] (72%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Gun_Shoot' | 'CharacterArmature|HitRecieve' | 'CharacterArmature|HitRecieve_2' | 'CharacterArmature|Idle' | 'CharacterArmature|Idle_Gun' | 'CharacterArmature|Idle_Gun_Pointing' | 'CharacterArmature|Idle_Gun_Shoot' | 'CharacterArmature|Idle_Neutral' | 'CharacterArmature|Idle_Sword' | 'CharacterArmature|Interact' | 'CharacterArmature|Kick_Left' | 'CharacterArmature|Kick_Right' | 'CharacterArmature|Punch_Left' | 'CharacterArmature|Punch_Right' | 'CharacterArmature|Roll' | 'CharacterArmature|Run' | 'CharacterArmature|Run_Back' | 'CharacterArmature|Run_Left' | 'CharacterArmature|Run_Right' | 'CharacterArmature|Run_Shoot' | 'CharacterArmature|Sword_Slash' | 'CharacterArmature|Walk' | 'CharacterArmature|Wave'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Suit_Legs: THREE.SkinnedMesh
    Suit_Feet: THREE.SkinnedMesh
    Suit_Head_1: THREE.SkinnedMesh
    Suit_Head_2: THREE.SkinnedMesh
    Suit_Head_3: THREE.SkinnedMesh
    Suit_Head_4: THREE.SkinnedMesh
    Suit_Body_1: THREE.SkinnedMesh
    Suit_Body_2: THREE.SkinnedMesh
    Suit_Body_3: THREE.SkinnedMesh
    Suit_Body_4: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/Business Man-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <skinnedMesh name="Suit_Legs" geometry={nodes.Suit_Legs.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Legs.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Suit_Feet" geometry={nodes.Suit_Feet.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Feet.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <group name="Suit_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="Suit_Head_1" geometry={nodes.Suit_Head_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Head_1.skeleton} />
          <skinnedMesh name="Suit_Head_2" geometry={nodes.Suit_Head_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Head_2.skeleton} />
          <skinnedMesh name="Suit_Head_3" geometry={nodes.Suit_Head_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Head_3.skeleton} />
          <skinnedMesh name="Suit_Head_4" geometry={nodes.Suit_Head_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Head_4.skeleton} />
        </group>
        <group name="Suit_Body" position={[0, 0.007, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="Suit_Body_1" geometry={nodes.Suit_Body_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Body_1.skeleton} />
          <skinnedMesh name="Suit_Body_2" geometry={nodes.Suit_Body_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Body_2.skeleton} />
          <skinnedMesh name="Suit_Body_3" geometry={nodes.Suit_Body_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Body_3.skeleton} />
          <skinnedMesh name="Suit_Body_4" geometry={nodes.Suit_Body_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Suit_Body_4.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Business Man-transformed.glb')
